### ISSUE TITLE
README: use cat / options

### ISSUE THREAD

**Issue by blueyed** [The-Compiler/sshtunnel#2]
For security reasons you might want to recommend using the following in `~/.ssh/authorized_keys` (before the key):

```
command="/bin/cat",no-pty,no-X11-forwarding,no-agent-forwarding
```

**Comment by The-Compiler** [comment]
The readme already recommends creating a new user with `/bin/false` as the shell. What does this improve over that recommendation? (honest question, because I have no idea)

**Comment by blueyed** [comment]
Yes, I've noticed that, but thought that it might still be possible to run programs - which does not seem to be the case.

The `command=` approach seems to be necessary/useful only in case you actually want to run some program and/or the user is used not only for tunnelling.

Thanks for a nice tool, closing the issue.
